# -*- coding: utf-8 -*-
"""ETL_IoT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17RnXlZVq8AaH4xLN6Hobjtl5J7LDCRmW

# **PARTE 1 — Limpieza**

# Importar librerías
"""

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# Leer el archivo"""

df = pd.read_json('/content/Datos_SIATA_Aire_pm25.json')

df.head()

df.shape

df.columns

"""# Identificar la estructura"""

print("Número de estaciones:", len(df))

print("\nColumnas:")
print(df.columns.tolist())

print("\nEstructura de una estación:")
print(df.iloc[0])

"""# Expandir datos"""

df = df.explode('datos')
df.head()

datos_expandido = pd.json_normalize(df['datos'])

datos_expandido.head()

"""# Unir la información de la estación con las mediciones"""

df = df.drop(columns='datos').reset_index(drop=True)

df = pd.concat([df, datos_expandido], axis=1)

df.head()

df.shape

"""# Revisar tipos de datos"""

df.info()

df['fecha'] = pd.to_datetime(df['fecha'])

df.info()

"""# Diagnóstico de nulos"""

df.isnull().sum()

"""# Datos faltantes"""

# Verificar horas faltantes por estación

fecha_min = df['fecha'].min()
fecha_max = df['fecha'].max()

fechas_esperadas = pd.date_range(
    start=fecha_min,
    end=fecha_max,
    freq='h'
)

for sensor, grupo in df.groupby('codigoSerial'):

    fechas_sensor = pd.DatetimeIndex(grupo['fecha'])

    faltantes = fechas_esperadas.difference(fechas_sensor)

    print(
        sensor,
        "→",
        len(faltantes),
        "horas faltantes"
    )

"""# Diagnóstico de duplicados"""

df.duplicated().sum()

df.duplicated(subset=['codigoSerial', 'fecha']).sum()

"""# Estadística descriptiva"""

df['valor'].describe()

"""# Buscar valores negativos"""

(df['valor'] < 0).sum()

(df['valor'] == -9999).sum()

"""# Buscar valores extremadamente altos"""

(df['valor'] > 1000).sum()

(df['valor'] > 50000).sum()

# Detectar outliers mediante IQR

Q1 = df['valor'].quantile(0.25)
Q3 = df['valor'].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

print("Límite inferior:", limite_inferior)
print("Límite superior:", limite_superior)

outliers = df[
    (df['valor'] < limite_inferior) |
    (df['valor'] > limite_superior)
]

print("Número de outliers:", len(outliers))

"""# Ver gráficamente los valores"""

df_validos = df[
    (df['valor'] >= 0) &
    (df['valor'] <= 500)
]

plt.figure(figsize=(10,5))

plt.hist(df_validos['valor'], bins=50)

plt.xlabel('PM2.5')
plt.ylabel('Frecuencia')
plt.title('Distribución exploratoria de PM2.5 (0–500)')

plt.show()

# Comportamiento promedio por hora

df_validos = df[
    (df['valor'] >= 0) &
    (df['valor'] <= 500)
].copy()

df_validos['hora'] = df_validos['fecha'].dt.hour

promedio_hora = (
    df_validos
    .groupby('hora')['valor']
    .mean()
)

plt.figure(figsize=(10,5))

plt.plot(
    promedio_hora.index,
    promedio_hora.values,
    marker='o'
)

plt.xlabel('Hora del día')
plt.ylabel('PM2.5 promedio')
plt.title('Comportamiento promedio de PM2.5 por hora')

plt.xticks(range(24))
plt.grid()

plt.show()

"""# Corrección de datos"""

df = df.sort_values(
    ['codigoSerial', 'fecha']
).reset_index(drop=True)

"""Convertir en NaN los valores que diagnosticamos como problemáticos."""

df['valor_original'] = df['valor']

df.loc[df['valor'] == -9999, 'valor'] = np.nan
df.loc[df['valor'] < 0, 'valor'] = np.nan
df.loc[df['valor'] > 1000, 'valor'] = np.nan

print("Valores anómalos convertidos a NaN:",
      df['valor'].isna().sum())

"""# Interpolación lineal"""

print("Valores faltantes antes de interpolar:",
      df['valor'].isna().sum())

df['valor_interpolado'] = (
    df.groupby('codigoSerial')['valor']
      .transform(lambda x: x.interpolate(method='linear'))
)

print("Valores faltantes después de interpolar:",
      df['valor_interpolado'].isna().sum())

"""# Reemplazar el valor original"""

df['valor'] = df['valor_interpolado']

df = df.drop(columns='valor_interpolado')

"""Guardar el archivo corregido"""

# Guardar el DataFrame corregido como JSON
nombre_archivo = 'Datos_SIATA_Aire_pm25_corregido.json'

df.to_json(
    nombre_archivo,
    orient='records',
    date_format='iso',
    force_ascii=False
)

print(f'Archivo guardado como: {nombre_archivo}')
